### PR TITLE
docs: add shields and menu

### PR DESCRIPTION
**Pull request by zachferland**

### CODE REVIEW

**Comment by zachferland** [comment]
@michaelsena looks like you have enable something/widget for the discord shield to show some stats

**Comment by michaelsena** [comment]
I enabled the widget @zachferland, is there some URL or code needed for it to pull member numbers?

**Comment by zachferland** [comment]
@michaelsena prefer member number vs number online? can see if that is an option

**Comment by zachferland** [comment]
nvm, this is the only option for now

**Pull request merged**
