### PR TITLE
update address server url

### PR DESCRIPTION
**Pull request by c-castillo**
Updated the address server URL

### CODE REVIEW

**Comment by c-castillo** [comment]
@oed yes it seems. I was using `prettier-standard` for formatting. In the weekend I did a clean install and I'm just using `standard` to format so we don't will have this styling conflicts in the future.

**Comment by oed** [comment]
@c-castillo I was still testing this, it was not ready to be merged yet!

**Comment by c-castillo** [comment]
🙈

**Comment by oed** [comment]
Seems like there are still some issues with the request done to the address-server. Anyway I'll fix those in a new PR.

**Comment by oed** [comment]
@c-castillo But in general don't merge PRs before you have at least one person that has approved :)

**Pull request merged**
